apiVersion: v1
kind: Service
metadata:
  name: jekyll-node-service
  namespace: development
  labels:
    app: jekyll
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: jekyll 